# Example Code generated by Beijing Volcanoengine Technology.
from __future__ import print_function
import volcenginesdkcore
import volcenginesdkark
from volcenginesdkcore.rest import ApiException

if __name__ == '__main__':
    # 注意示例代码安全，代码泄漏会导致AK/SK泄漏，有极大的安全风险。
    configuration = volcenginesdkcore.Configuration()
    configuration.ak = "AKLTYWYxZTY1YjA5ZGM1NGJlMGEzMmViZDRkOWYzZDVlODM"
    configuration.sk = "WldSaVpEWTBNVEU1TWpaa05HWmhabUV3TjJFNE9UQXlORGxoWkRCbE1HTQ=="
    configuration.region = "cn-beijing"
    # set default configuration
    volcenginesdkcore.Configuration.set_default(configuration)

    # use global default configuration
    api_instance = volcenginesdkark.ARKApi()
    get_api_key_request = volcenginesdkark.GetApiKeyRequest(
        duration_seconds=9999,
        resource_ids=[
            "有哪些让你颠覆三观的社会真相?社会不教,精英不说,有些东西没人点拨,你未必知道,普通人如何破局。说直白一点,通透一点,可以说脏话!"],
        resource_type="99999",
    )

    try:
        # 复制代码运行示例，请自行打印API返回值。
        api_instance.get_api_key(get_api_key_request)
    except ApiException as e:
        # 复制代码运行示例，请自行打印API错误信息。
        # print("Exception when calling api: %s\n" % e)
        pass
